---
- name: Install python pip 
  package: name=python-pip state=present

- name: Install tree 
  package: name=tree state=present

- name: Install C dev tools
  package: name={{ item }} state=present
  with_items:
    - clang
    - build-essential
    - cmake
    - python-dev
    - python3-dev
    - ipcalc
  ignore_errors: yes
  
- name: Install ruby and it's crap
  package: name={{ item }} state=present
  with_items:
    - ruby
    - ruby-dev
    - make
    - zlib1g-dev
    - libicu-dev 
  ignore_errors: yes

- name: Install gollum (the github wiki server)
  gem: name=gollum state=present 
  ignore_errors: yes 
