---
- name: Install build essential 
  apt: name=build-essential state=present

- name: Install python pip 
  apt: name=python-pip state=present

- name: Install tree 
  apt: name=tree state=present

- name: Install cmake 
  apt: name=cmake state=present

- name: Install ruby and it's crap
  apt: name={{ item }} state=present
  with_items:
    - ruby
    - ruby-dev
    - make
    - zlib1g-dev
    - libicu-dev 

- name: Install gollum (the github wiki server)
  gem: name=gollum state=present  
