---
- name: Install build essential 
  apt: name=build-essential state=present

- name: Install python pip 
  apt: name=python-pip state=present

- name: Install tree 
  apt: name=tree state=present

- name: Install ruby and it's crap
  apt: name=rubygems  
