---
- name: Install python pip 
  package: name=python-pip state=present

- name: Install tree 
  package: name=tree state=present

- name: Install C dev tools
  package: name={{ item }} state=present
  with_items:
    - clang
    - "@Development tools" 
    - cmake
    - python-devel
  ignore_errors: yes
  
- name: Install ruby and it's crap
  package: name={{ item }} state=present
  with_items:
    - ruby
    - ruby-devel
    - make
    - zlib-devel
    - libicu-devel 
  ignore_errors: yes

- name: Install vagrant
  gem: name=vagrant state=present

- name: Install gollum (the github wiki server)
  gem: name=gollum state=present 
  ignore_errors: yes 
