---
- name: Install python pip 
  apt: name=python-pip state=present

- name: Install tree 
  apt: name=tree state=present

- name: Install C dev tools
  apt: name={{ item }} state=present
  with_items:
    - clang
    - build-essential
    - cmake
    - python-dev
    - python3-dev
    - ipcalc
  
- name: Install ruby and it's crap
  apt: name={{ item }} state=present
  with_items:
    - ruby
    - ruby-dev
    - make
    - zlib1g-dev
    - libicu-dev 

- name: Install gollum (the github wiki server)
  gem: name=gollum state=present  
