---
- name: Install docker 
  package: name=docker state=present 

- name: Start and enable docker daemon during boot
  systemd: 
    name: docker
    state: started
    enabled: True 
    
- name: Create docker group
  group:
    name: docker
    state: present

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
