---
- name: Install git
  apt: name=git state=present

- name: Set name
  command: git config --global user.name {{ username }}
 
- name: Set email 
  command: git config --global user.name {{ email }}
 
- name: Turn off ssl verify
  command: git config --global http.sslVerify false 

 
